### ISSUE TITLE
STACK_YAML environment variable borks intero-neovim

### ISSUE THREAD

**Issue by lwm** [parsonsmatt/intero-neovim#38] opened 2017-03-31 00:13 UTC
Saw this running intero while rooting around in https://github.com/commercialhaskell/stack.

Could be a duplicate of https://github.com/parsonsmatt/intero-neovim/issues/32?

```
Invalid argument `project'
File does not exist or is not a regular file `--stack-yaml'

Usage: stack [--help] [--version] [--numeric-version] [--hpack-numeric-version]
             [--docker*] [--nix*] ([--verbosity VERBOSITY] | [-v|--verbose] |
             [--silent]) [--[no-]time-in-log] [--stack-root STACK-ROOT]
             [--work-dir WORK-DIR] [--[no-]system-ghc] [--[no-]install-ghc]
             [--arch ARCH] [--ghc-variant VARIANT] [--ghc-build BUILD]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]
             [--with-gcc PATH-TO-GCC] [--[no-]skip-ghc-check] [--[no-]skip-msys]
             [--local-bin-path DIR] [--[no-]modify-code-page]
             [--[no-]allow-different-user] [--[no-]dump-logs]
             [--resolver RESOLVER] [--compiler COMPILER] [--[no-]terminal]
             [--color WHEN] [--stack-yaml STACK-YAML] COMMAND|FILE

[Process exited 1]
```

**Comment by rdnetto** [comment] 2017-03-31 10:50
Which version of Stack are you using? The root cause of #32 is that we don't handle Stack <=1.2 correctly atm, so updating to the latest version should work-around that.

**Comment by lwm** [comment] 2017-03-31 19:41
> Which version of Stack are you using? The root cause of #32 is that we don't handle Stack <=1.2 correctly atm, so updating to the latest version should work-around that.

Hmmm, I build it from source, so, at the latest commit.

**Comment by rdnetto** [comment] 2017-04-02 00:34
Well that's really odd. What's the output of `stack --version`?

**Comment by lwm** [comment] 2017-04-02 10:17
```
λ ~/hobby/stack/ master stack --version
Version 1.4.1, Git revision bac50451b559a8ad4cf8d40b56ea007cf4154324 (dirty) (4666 commits) x86_64 
...
```

**Comment by lwm** [comment] 2017-04-02 10:19
I use the `STACK_YAML` environment variable though! Could that be part of this?

```
λ ~/hobby/stack/ master env | grep -i yaml
STACK_YAML=stack.yaml
λ ~/hobby/stack/ master 
```

**Comment by rdnetto** [comment] 2017-04-04 11:27
It looks like that might be the cause:

     /home/reuben$ stack path --config-location
    /home/reuben/.stack/global-project/stack.yaml

    /home/reuben/scratch$ stack path --config-location
    /home/reuben/scratch/stack.yaml

    /home/reuben$ env STACK_YAML=/home/reuben/scratch/stack.yaml stack path --config-location
    Getting project config file from STACK_YAML environment
    /home/reuben/scratch/stack.yaml

On investigation, 'Getting project config file from STACK_YAML environment' is printed to stderr, but the filename is printed to stdout, so it looks like Stack does the right thing here. However, we call stack with `systemlist()`, which collects data written to both stdout and stderr. There isn't an easy way to tell systemlist to ignore stderr, but since we're currently doing the hacky thing of only looking at the first line of the output, we might as well change the hack to only look at the last line of the output.

**Comment by rdnetto** [comment] 2017-04-04 11:31
I've pushed a fix - can you try checking it out and seeing if you can reproduce the problem?

**Comment by lwm** [comment] 2017-04-04 13:12
Thanks! I upgraded and got:
```
Invalid argument `http://docs.haskellstack.org/en/stable/yaml_configuration/'
File does not exist or is not a regular file `--stack-yaml' 
...
```

I can confirm that when I unset the `STACK_YAML` variable, everything works :smile:

**Comment by parsonsmatt** [comment] 2017-07-15 21:56
@lwm Would you be willing to check out #63 and see if that fixes your issue? I've tried it on my local setup and it works for me.

One gotcha is that the STACK_YAML environment variable seems to be interpreted with respect to the *file* that is currently open. So given:

```
src/Lib.hs
stack.yaml

$ STACK_YAML=stack.yaml nvim src/Lib.hs
```

it will attempt to do `stack --stack-yaml src/stack.yaml`. So the value in `STACK_YAML` must be an absolute location, otherwise it'll be interpreted erroneously.

**Closed** 2017-07-16 05:18 UTC
Labels: bug

**Comment by lwm** [comment] 2017-07-17 10:40
Thanks @parsonsmatt! Just seeing this now, works a treat :beers:
