### ISSUE TITLE
Eval visual selection

### ISSUE THREAD

**Issue by lpil** [parsonsmatt/intero-neovim#48] opened 2017-07-02 20:46 UTC
I would like to be able to visually select some code and evaluate it. This would be especially useful for live-coding art and music with tools such as Tidal (https://tidalcycles.org/).

Thanks,
Louis

**Comment by parsonsmatt** [comment] 2017-07-02 22:55
This is a duplicate of #3. It seems like it would be really useful but very often wouldn't work out all that great.

We can reopen #3 if we figure out how to handle missing terms. I suppose it wouldn't be too hard to send

```
:{
<<visual mode paste>>
:}
```

and let the user define those missing terms themselves.

**Comment by lpil** [comment] 2017-07-02 22:57
That's the usual approach in my experience :)

**Comment by jez** [comment] 2017-07-15 21:18
For any enterprising people who stumble onto this issue: the overall machinery for getting the selection and then `eval`'ing something afterwords now exists due to #59. It's now a matter of adapting/copying the code for getting a selection to eval it afterwards.

**Closed** 2019-06-29 14:47 UTC
Labels: beginner friendly, enhancement
